"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useQuery, useMutation } from "convex/react";
import { api } from "../../../convex/_generated/api";

export function ReportsDashboard() {
  const convexReports = useQuery(api.reports.getReports);
  const reports = convexReports || [];
  const deleteReport = useMutation(api.reports.deleteReport);
  const router = useRouter();

  return (
    <div className="max-w-7xl mx-auto space-y-8">
      {/* Header Section */}
      <section className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <h3 className="text-4xl font-headline font-extrabold tracking-tight text-white">Saved Reports</h3>
          <p className="text-on-surface-variant mt-2 max-w-xl">Analyze channel performance, audience retention metrics, and competitive benchmarks generated by VidMetrics AI.</p>
        </div>
        <Link href="/reports/new" className="inline-flex items-center justify-center gap-2 px-6 py-3.5 bg-gradient-to-br from-secondary to-secondary-container text-white font-bold rounded-xl shadow-lg active:scale-95 transition-all w-fit">
          <span className="material-symbols-outlined">add</span>
          <span>New Report</span>
        </Link>
      </section>

      {/* List content starts here directly */}

      {/* Reports List */}
      <section className="space-y-4">
        {/* Report Header Labels (Desktop) */}
        <div className="hidden md:grid grid-cols-12 px-6 py-2 text-[10px] font-bold uppercase tracking-widest text-on-surface-variant/60">
          <div className="col-span-4">Channel &amp; Report Name</div>
          <div className="col-span-2">Time Range</div>
          <div className="col-span-2">Date Generated</div>
          <div className="col-span-2">Status</div>
          <div className="col-span-2 text-right">Actions</div>
        </div>

        {reports.map((report) => {
          const isComplete = report.status === "complete";
          const isGenerating = report.status === "generating" || report.status === "queued";
          const isFailed = report.status === "failed";
          
          return (
            <div
              key={report._id}
              onClick={() => { if (isComplete) router.push(`/reports/${report._id}`); }}
              className={`grid grid-cols-1 md:grid-cols-12 items-center px-6 py-5 bg-surface-container-low hover:bg-surface-container transition-colors rounded-2xl gap-4 ${isComplete ? 'border-l-4 border-secondary/40 cursor-pointer' : ''}`}
            >
              <div className="col-span-4 flex items-center gap-4">
                <div className={`w-12 h-12 rounded-lg bg-surface-container-highest flex items-center justify-center overflow-hidden shrink-0 ${isFailed ? 'opacity-50 grayscale' : ''}`}>
                  {report.channelAvatarUrl ? <img src={report.channelAvatarUrl} alt="Avatar" crossOrigin="anonymous" referrerPolicy="no-referrer" className="w-full h-full object-cover" /> : <span className="text-xl font-bold text-white">V</span>}
                </div>
                <div>
                  <p className={`font-bold ${isFailed ? 'text-on-surface-variant' : 'text-white'}`}>{report.channelName || report.channelUrlInput}</p>
                  <p className={`text-xs ${isFailed ? 'text-on-surface-variant/50' : 'text-on-surface-variant'}`}>{report.channelHandle}</p>
                </div>
              </div>
              <div className="col-span-2">
                <span className={`text-sm font-medium ${isFailed ? 'text-on-surface-variant/60' : 'text-on-surface'}`}>{report.dateRange}</span>
              </div>
              <div className="col-span-2">
                <span className={`text-sm ${isFailed ? 'text-on-surface-variant/60' : 'text-on-surface-variant'}`}>
                  {new Date(report.createdAt).toLocaleDateString()}
                </span>
              </div>
              <div className="col-span-2">
                {isComplete && (
                  <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-secondary/10 text-secondary text-xs font-bold rounded-full">
                    <span className="w-1.5 h-1.5 rounded-full bg-secondary"></span>
                    Complete
                  </div>
                )}
                {isGenerating && (
                  <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-tertiary/10 text-tertiary text-xs font-bold rounded-full">
                    <span className="w-1.5 h-1.5 rounded-full bg-tertiary"></span>
                    Generating
                  </div>
                )}
                {isFailed && (
                  <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-error/10 text-error text-xs font-bold rounded-full">
                    <span className="material-symbols-outlined text-[10px]" style={{ fontVariationSettings: "'FILL' 1" }}>error</span>
                    Failed
                  </div>
                )}
              </div>
              <div className="col-span-2 flex justify-end gap-2">
                {isGenerating ? (
                  <div className="w-8 h-8 flex items-center justify-center">
                    <span className="material-symbols-outlined animate-spin text-tertiary">sync</span>
                  </div>
                ) : isFailed ? (
                  <>
                    <button className="p-2 bg-surface-variant text-on-surface rounded-lg hover:text-white transition-all">
                      <span className="material-symbols-outlined text-sm">refresh</span>
                    </button>
                    <button onClick={() => deleteReport({ reportId: report._id })} className="p-2 bg-surface-variant text-on-surface rounded-lg hover:text-error transition-all">
                      <span className="material-symbols-outlined text-sm">delete</span>
                    </button>
                  </>
                ) : (
                  <>
                    <Link href={`/reports/${report._id}`} onClick={(e) => e.stopPropagation()} className="p-2 bg-surface-variant text-on-surface rounded-lg hover:bg-secondary/20 hover:text-secondary transition-all flex items-center justify-center">
                      <span className="material-symbols-outlined text-sm">visibility</span>
                    </Link>
                    <button onClick={(e) => { e.stopPropagation(); deleteReport({ reportId: report._id }); }} className="p-2 bg-surface-variant text-on-surface rounded-lg hover:text-error transition-all">
                      <span className="material-symbols-outlined text-sm">delete</span>
                    </button>
                  </>
                )}
              </div>
            </div>
          );
        })}
      </section>

      {/* Bottom Pagination */}
      <section className="flex items-center justify-between pt-6 border-t border-outline-variant/10">
        <p className="text-sm text-on-surface-variant">Showing <span className="text-white font-bold">{reports.length}</span> of <span className="text-white font-bold">{reports.length}</span> reports</p>
        <div className="flex gap-2">
          <button className="p-2 bg-surface-container text-on-surface-variant rounded-lg hover:text-white transition-colors disabled:opacity-30" disabled>
            <span className="material-symbols-outlined">chevron_left</span>
          </button>
          <button className="p-2 bg-surface-container text-on-surface-variant rounded-lg hover:text-white transition-colors">
            <span className="material-symbols-outlined">chevron_right</span>
          </button>
        </div>
      </section>
    </div>
  );
}
